package Pages;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

/**
 *
 * @author samidhamanjrekar
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans NKo", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gurmukhi MT", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Gurmukhi MT", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, 300, -1));

        jTextField1.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 300, -1));

        jButton1.setFont(new java.awt.Font("Gurmukhi MT", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Submit");
        jButton1.setBorder(null);
        jButton1.setPreferredSize(new java.awt.Dimension(76, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, 110, 40));

        jButton2.setFont(new java.awt.Font("Gurmukhi MT", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Reset");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 510, 100, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close copy.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1298, 16, -1, -1));

        jButton4.setFont(new java.awt.Font("Gurmukhi MT", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Create Account");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButton(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, 260, 40));

        jButton5.setForeground(new java.awt.Color(81, 182, 182));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye2.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordVisibleInvisible(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 380, 50, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home copy.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton
        // Reset button
        jTextField1.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_resetButton

    private void createAccountButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButton
        // Create Account button
        setVisible(false);
        new Registration().setVisible(true);
    }//GEN-LAST:event_createAccountButton

    private void submitButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton
        // Submit button
        try {
            Connection con = ConnectionProvider.getCon();
            Statement stmt = con.createStatement();

            String userName = jTextField1.getText();
            String password = new String(jPasswordField1.getPassword());

            if (userName.isEmpty() || password.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter both username and password!", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String query = "SELECT * FROM USER WHERE UserName = '" + userName + "' AND Password = '" + password + "'";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                String role = rs.getString("Role");
                String name = rs.getString("Name");
                if (role.equalsIgnoreCase("Admin")) {
                    setVisible(false);
                    new Admin_Dashboard(userName, name).setVisible(true);
                } else {
                    setVisible(false);
                    new Pharmacist_Dashboard(userName, name).setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect User Name or Password!");
            }
            con.close();
            rs.close();
            stmt.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error occurred while logging in: " + e.getMessage());
        }
    }//GEN-LAST:event_submitButton

    private void closeButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton
        // Close button
        int a = JOptionPane.showConfirmDialog(null, "Do you want to close page?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeButton

    private void passwordVisibleInvisible(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordVisibleInvisible
        // Password visible / invisible

        if (flag == 0) {
            jButton5.setIcon(new ImageIcon("/Users/samidhamanjrekar/NetBeansProjects/PharmacyManagementSystem/src/Images/eye2.png"));
            flag = 1;
            jPasswordField1.setEchoChar('*');
        } else {
            jButton5.setIcon(new ImageIcon("/Users/samidhamanjrekar/NetBeansProjects/PharmacyManagementSystem/src/Images/eye.png"));
            flag = 0;
            jPasswordField1.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordVisibleInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private int flag = 0;
}
