package Pages;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dao.ConnectionProvider;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author samidhamanjrekar
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans NKo", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registration Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 229, 220));
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 160, -1));

        jLabel3.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 226, 216));
        jLabel3.setText("User Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 160, -1));

        jLabel4.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 226, 216));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 148, -1));

        jLabel5.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(127, 226, 216));
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(127, 226, 216));
        jLabel6.setText("Date Of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(127, 226, 216));
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 560, 160, -1));

        jLabel8.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(127, 226, 216));
        jLabel8.setText("Phone Number");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        jTextField1.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField1.setPreferredSize(new java.awt.Dimension(64, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 360, 30));

        jTextField2.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField2.setPreferredSize(new java.awt.Dimension(64, 30));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                checkUsername(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 360, -1));

        jPasswordField1.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(64, 30));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 360, -1));

        jPasswordField2.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPasswordField2.setPreferredSize(new java.awt.Dimension(64, 30));
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 360, -1));

        jLabel9.setFont(new java.awt.Font("Gurmukhi MT", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(127, 226, 216));
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1308, 583, -1, -1));

        jTextField5.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField5.setPreferredSize(new java.awt.Dimension(64, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 490, 360, -1));

        jTextField6.setFont(new java.awt.Font("Gurmukhi MT", 0, 18)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextField6.setPreferredSize(new java.awt.Dimension(64, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 430, 360, -1));

        jButton1.setBackground(new java.awt.Color(98, 182, 174));
        jButton1.setFont(new java.awt.Font("Gurmukhi MT", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, 130, 40));

        jButton2.setBackground(new java.awt.Color(97, 181, 172));
        jButton2.setFont(new java.awt.Font("Gurmukhi MT", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButton(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 670, 130, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close copy.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButton(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Gurmukhi MT", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 550, 360, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 360, 30));

        jLabel11.setPreferredSize(new java.awt.Dimension(30, 30));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 190, -1, 30));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye4.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordVisibleInvisible(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 250, -1, -1));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye4.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordVisibleInvisible2(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 310, 48, 30));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1022, 101, -1, -1));

        jButton4.setBackground(new java.awt.Color(97, 181, 172));
        jButton4.setFont(new java.awt.Font("Gurmukhi MT", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.setBorder(null);
        jButton4.setPreferredSize(new java.awt.Dimension(61, 32));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginButton(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, 130, 40));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 101, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background3.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton
        // Submit button to add user details into the dateabase

        String name = jTextField1.getText();
        String userName = jTextField2.getText();
        String password = new String(jPasswordField1.getPassword());
        String confirmPassword = new String(jPasswordField2.getPassword());
        String address = jTextArea1.getText();
        String phone = jTextField5.getText();
        String email = jTextField6.getText();
        String dateOfBirth = "";
        Date selectedDate = jDateChooser1.getDate();
        Date currentDate = new Date();

        if (selectedDate != null) {
            if (selectedDate.after(currentDate)) {
                JOptionPane.showMessageDialog(this, "Invalid Date Of Birth!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
            dateOfBirth = dFormat.format(selectedDate);
        }

        if (name.isEmpty() || userName.isEmpty() || password.isEmpty() || confirmPassword.isEmpty() || address.isEmpty() || phone.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Password does not match the confirm password!", "Error", JOptionPane.ERROR_MESSAGE);
            jPasswordField1.setText("");
            jPasswordField2.setText("");
        } else if (phone.length() != 10 || !phone.matches(phonePattern)) {
            JOptionPane.showMessageDialog(this, "Invalid phone number!", "Error", JOptionPane.ERROR_MESSAGE);
            jTextField5.setText("");
        } else {
            try {
                Connection con = ConnectionProvider.getCon();
                String sql = "INSERT INTO USER (name, username, password, dateOfBirth, address, phone, email) "
                        + "VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setString(1, name);
                stmt.setString(2, userName);
                stmt.setString(3, password);
                stmt.setString(4, dateOfBirth);
                stmt.setString(5, address);
                stmt.setString(6, phone);
                stmt.setString(7, email);

                stmt.executeUpdate();
                JOptionPane.showMessageDialog(null, "Account created successfully!");
                setVisible(false);
                new PharmacistDashboard(userName, name).setVisible(true);

                con.close();
                stmt.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error occurred while registering user: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitButton

    private void closeButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButton
        // Exit Button
        int exit = JOptionPane.showConfirmDialog(null, "Do you want to close page?", "Select", JOptionPane.YES_NO_OPTION);
        if (exit == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeButton

    private void resetButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButton
        // Reset Button
        jTextField1.setText("");
        jTextField2.setText("");
        jDateChooser1.setDate(null);
        jTextArea1.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }//GEN-LAST:event_resetButton


    private void checkUsername(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkUsername
        // Tick or Cross to show if the username is taken or not and also checks if it is taken
        check = 0;
        String userName = jTextField2.getText();
        if (!userName.isEmpty()) {
            try {
                Connection con = ConnectionProvider.getCon();
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM USER WHERE username = '" + userName + "'");
                if (rs.next()) {
                    check = 1;
                    jLabel11.setVisible(true);
                    jLabel11.setIcon(new ImageIcon("/Users/samidhamanjrekar/NetBeansProjects/PharmacyManagementSystem/src/Images/cross.png"));
                    jLabel11.setText("");
                } else {
                    jLabel11.setVisible(true);
                    jLabel11.setIcon(new ImageIcon("/Users/samidhamanjrekar/NetBeansProjects/PharmacyManagementSystem/src/Images/tick.png"));
                    jLabel11.setText("");
                }
                con.close();
                stmt.close();
                rs.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            jLabel11.setVisible(false);
        }
    }//GEN-LAST:event_checkUsername

    private void passwordVisibleInvisible(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordVisibleInvisible
        // Password visible/invisible
        if (flag == 0) {
            jButton6.setIcon(new ImageIcon(getClass().getResource("/Images/eye4.png")));
            flag = 1;
            jPasswordField1.setEchoChar('*');
        } else {
            jButton6.setIcon(new ImageIcon(getClass().getResource("/Images/eye3.png")));
            flag = 0;
            jPasswordField1.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordVisibleInvisible

    private void passwordVisibleInvisible2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordVisibleInvisible2
        // Password visible/invisible
        if (flag == 0) {
            jButton7.setIcon(new ImageIcon(getClass().getResource("/Images/eye4.png")));
            flag = 1;
            jPasswordField2.setEchoChar('*');
        } else {
            jButton7.setIcon(new ImageIcon(getClass().getResource("/Images/eye3.png")));
            flag = 0;
            jPasswordField2.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_passwordVisibleInvisible2

    private void backToLoginButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginButton
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_backToLoginButton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
    private int flag;
    private int check;
    private final String phonePattern = "^[0-9]*$";

}
